epochs: 50
batch_size: 8
description: null
seed: 41
verbose: true
output_name: finetune_models
custom_name: __Mobile-CMUNeXt__Quant_W8__FinalV2__
model: Mobile-CMUNeXt-Quant-RELU-BN-ACT
input_channels: 3
num_classes: 1
input_w: 256
input_h: 256
dims:
- 8
- 8
- 16
- 16
- 24
depths: null
kernels: null
data_dir: ../../data/
dataset_name: FIVES2022
img_ext: .png
mask_ext: .png
optimizer: Adam
lr: 0.001
momentum: 0.9
weight_decay: 0.0001
nesterov: false
scheduler: CosineAnnealingLR
T_max: 0.001
min_lr: 1.0e-05
eta_min: 1.0e-05
exponent: 0.9
factor: 0.1
patience: 2
milestones: 1,2
gamma: 0.6666666666666666
cfg: null
early_stopping: -1
num_workers: 8
act_bit_width: 8
weight_bit_width: 8
bias_bit_width: 16
datetime: 2025-09-25_11h09m34s
model_dir: /home/antonio/medical-image-semantic-segmentation/src/python/finetune_models/__Mobile-CMUNeXt__Quant_W8__FinalV2__/FIVES2022/2025-09-25_11h09m34s
end_datetime: 2025-09-25_11h20m12s
bn: false
